apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marvel
  template:
    metadata:
      name: heroes
      labels:
        app: marvel
    spec:
      containers:
        - name: server
          image: nginx
        - name: cache
          image: redis